#! /bin/bash

# The path to the folder containing the jar
FILE_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# The fully qualified name of the class to execute
CLASS="lukfor.tables.App"

CLASS_PATH="$FILE_PATH/magic-tables.jar"


# execute cloudgene
java -cp $CLASS_PATH $CLASS "$@"
